# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pokoù - La Matrice
email: pokou@lamatrice.com
description: > # this means to ignore newlines until "baseurl:"
  Bienvenue au pays des pokoù
baseurl: "/pokou" # the subpath of your site, e.g. /blog
locale: fr # the primary language of your content

# Build settings
markdown: kramdown
